### ISSUE TITLE
Quick Code Review 11/02/2025

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/iac-helm-neulander#1]
This ticket will contain the output from a quick cursory code review

**Comment by qcaas-nhs-sjt** [comment]
Namespaces should not be specified within the helm chart unless absolutely necessary, they should be assigned by the helm install command

https://github.com/lsc-sde/iac-helm-neulander/blob/e54a5f29080c90daad16b4c88376925e5a80d1ec/templates/api.yaml#L9

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L82

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/ingress.yaml#L6

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/medcat_14.yaml#L8

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/medcat_14.yaml#L90

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/rmq.yaml#L5

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/rmq.yaml#L38

**Comment by qcaas-nhs-sjt** [comment]
I would recommend splitting all the files and creating a folder hierarchy instead, so for example have a folder for the API then under this have the resources pertaining to that api in separate files. So api.yaml becomes:

```
./api/deployment.yaml
./api/service.yaml
```

This will make the code easier to read and manage.

**Comment by qcaas-nhs-sjt** [comment]
ideally resources should be named dynamically, and default to a name based around the helm chart release. You should be able to override these. I see you've got some of this logic in helpers already but doesn't seem to be implemented on the resources themselves

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/_helpers.tpl#L1-L6

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L8

**Comment by qcaas-nhs-sjt** [comment]
I would suggest instead of using the Chart name (which is static), use the release name as this gives more flexibility when designing the chart

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/_helpers.tpl#L5

would become:

```helm
{{- default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
```

**Comment by qcaas-nhs-sjt** [comment]
I would prefix labels with a organisation name to know where these came from and make them unique:

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L11

would become

```yaml
xlscsde.nhs.uk/app: neulander-api
```

I know it seems to be fairly unique anyway but you'll be surprised how often people will come up with similar product names

**Comment by qcaas-nhs-sjt** [comment]
Rather than making the image name a composite like this, i would suggest keep it simple and just expose the image name as a variable. The composite can happen on the other side giving more freedom.

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L24

would become:

```
  image: {{ .Values.api.image.name }}
```
This allows the implementing organisation to composite how they see fit and would allow them to maybe use one repository for one image and a different one for another. This is especially beneficial if they want to create their own custom image based on yours

**Comment by qcaas-nhs-sjt** [comment]
I would suggest that when using secrets that you allow the user to specify the name and key of the secret using variables

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L28-L53

A specific secret might look like this:

```yaml
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .values.rabbitmq.host.secret }}
                  key: {{ .values.rabbitmq.host.secretKey }}
...
```

then in your values file you just reflect this with the defaults you want:

```yaml
rabbitmq:
   host:
     secret: neulander-rmq-default-user
     secretKey: host
...
```

**Comment by qcaas-nhs-sjt** [comment]
Secrets add a layer of complexity that isn't really needed I would suggest keeping them to a minimum and either using config maps or literals associated with variables instead for things which aren't really secrets:

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L28-L43

would become

``` yaml
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user }}
```

**Comment by qcaas-nhs-sjt** [comment]
do not hard code unless absolutely necessary, make these available and consider whether you actually need anything else from the block in question. In some cases it might be preferable to simply expose the block in question.

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L54-L60

**Comment by qcaas-nhs-sjt** [comment]
Ports and protocols should be configurable if possible, other people may want to security harden the service, or make other changes to suit their environment. Only control these if you want to enforce something (in some of our templates we enforce them being secure ports instead of giving people the choice of shortcutting to a less secure version).

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L88-L91

**Comment by qcaas-nhs-sjt** [comment]
I would recommend giving ports names, then you can refer to the names via the services/ingresses rather than relying on the port number

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L26-L27

would become:

```yaml
          ports:
            - name: container-api
               containerPort: 8000
```

and

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/api.yaml#L88-L91

would become

```yaml
  ports:
    - name: svc-api
      protocol: TCP
      port: 80
      targetPort: container-api
```

and 

https://github.com/lsc-sde/iac-helm-neulander/blob/4812da2d3617e0e52a95b740b6cca3595ba4ee52/templates/ingress.yaml#L17-L26

would become:

```yaml
  - host: {{ $.host | quote }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: neulander-api
            port: 
              name: svc-api
```
